//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskTable
    {
        public int TaskId { get; set; }
        public string Title { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public string Status { get; set; }
        public System.DateTime CompDate { get; set; }
    }
}
